### ISSUE TITLE
Request <3

### ISSUE THREAD

**Issue by vasileioskorompilias** [Jeadie/notion-rss#3]
Hello, and what a wonderful little thing you have made! :)
Could you add a section for Description? I believe RSS offers this in the feeds. 

Cheers!

**Comment by Jeadie** [comment]
Let me have a look

**Comment by Jeadie** [comment]
Done --> https://github.com/Jeadie/notion-rss/commit/8a0e33b1546df1a8874d901375a2dda240022cf5
The one issue I found was that many RSS feeds that have descriptions, are HTML, so they don't have the best UI in the table view.

**Comment by Jeadie** [comment]
Closing, let me know if you have anything else
