### ISSUE TITLE
Working perfectly, manually, but I don't have a cron.yml ?

### ISSUE THREAD

**Issue by steveharman** [Jeadie/notion-rss#4]
This worked great for me, many thanks for the excellent work.

The only part I don't understand or have missed is having the feeds updated each day (via cron).  The setup instructions reference `.github/workflow/cron.yml` but the only file I have in my forked repo at  `.github/workflow/` is `main.yml `

Currently, the way I invoke `notion-rss` is to visit my fork of the repo > Actions > Get Feed > [Run Workflow]

Thanks again.

**Comment by Jeadie** [comment]
That's interesting. For reference, here is the cron file in the repo https://github.com/Jeadie/notion-rss/blob/main/.github/workflows/cron.yml. 

At worst, you could make a comment in your forked repo with the file.

**Comment by steveharman** [comment]
Many thanks.  What's interesting is that I do still seem to receive daily updates/refreshes of my feeds, even without the corn file.

I noticed there's this within `main.yml`

```
on:
  schedule:
    - cron: "30 12 * * *" # 6pm IST
  workflow_dispatch:

```
Which would appear to be some kind of cron based scheduling?

**Comment by Jeadie** [comment]
That is interesting. what's the diff between main.yml and cron.yml?
