### ISSUE TITLE
Run sucessfully but no data in database ( I change the time interval to 5 minutes) and also run by hands

### ISSUE THREAD

**Issue by YiZhiYuanYuan-qyy** [Jeadie/notion-rss#6]

**Comment by Jeadie** [comment]
Hi @YiZhiYuanYuan-qyy , this may be due to the fact the default RSS sweep is for the last 24 hours. We currently don't support backfill. If you change the duration [here](https://github.com/Jeadie/notion-rss/blob/main/tasks.go#L29-L31), from 24 hours so somehow longer, it may get results.
